run:
  timeout: 5m

linters:
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - sloglint
    - staticcheck
    - unparam
    - unused

issues:
  exclude-use-default: false
