name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - macos-14
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Verify
        run: make verify
